name: Mastodon
on:
    push:
        branches:
        - main

jobs:
    post-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@v3
            - name: Use secrets
            run: python3